source 'https://rubygems.org'

gem 'sinatra'
gem 'haml'
gem 'rubyzip', '1.2.1'
gem 'zip-zip', '0.3'
gem 'net-ldap'
gem 'json'
gem 'nokogiri'
gem 'do_sqlite3'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'msfrpc-client'
gem 'axlsx'
gem 'ots'
